### ISSUE TITLE
isEmpty will not work as expected

### ISSUE THREAD

**Issue by fc** [jakubkoci/react-form-validation#1]
Just a note that the `isEmpty` callback will not work as expected.  This will return true, not false.
```
'' && ''.length === 0
```

https://github.com/jakubkoci/react-form-validation/blob/master/src/components/getValidationSchema-spected.js#L27

Otherwise - thanks for taking the time with the blog post -- definitely prefer spected over yup, thank you!

**Comment by jakubkoci** [comment]
Yes, you're right. Thanks for the feedback. I've fixed it by e011582.
